apiVersion: v1
kind: ReplicationController
metadata:
  name: php-mysql-rc-@EDITAR_USUARIO@
  labels:
    user: @EDITAR_USUARIO@
    app: php-mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        user: @EDITAR_USUARIO@
        app: php-mysql
    spec:
      restartPolicy: Always
      containers:
        - name: mysql
          image: mysql:5.5
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mypass
          ports:
            - containerPort: 3306
        - name: php-mysql
          image: matuu/php-mysql-@EDITAR_USUARIO@:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mypass
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-mysql-svc-@EDITAR_USUARIO@
spec:
  type: NodePort
  ports:
    -
      port: 80
      targetPort: 80
  selector:
    user: @EDITAR_USUARIO@
    app: php-mysql
#   externalIPs:
#     - @EDITAR_EXTERNAL_IP@

# vim: si et sw=2 ts=2 syntax=yaml
